# Generated by Django 5.1.3 on 2024-12-13 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Chocolates',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=100)),
                ('weight', models.FloatField()),
                ('value', models.FloatField()),
                ('ratio', models.FloatField()),
                ('image', models.ImageField(blank=True, null=True, upload_to='chocolate/')),
            ],
        ),
    ]
